name = "BlanketCon 2022"
author = "The community!"
version = "2022.04.18"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dfe663701d71217eb04e02cd0799739ee096e065e5bedb90cd51735a21237c92"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
