name = "BlanketCon 2022"
author = "The community!"
version = "2022.04.23"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f05af263a76ef441a5b0a717df50d66ad1f8f740c4b2551cfd1722ab249fa54f"

[versions]
minecraft = "1.18.2"
quilt = "0.16.0-beta.10"
