name = "BlanketCon 2022"
author = "The community!"
version = "2022.04.20"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c30e7fac284176f72533bd2a8a6ba3ccde22b6bb33e43cbec11c4a05d34e9511"

[versions]
minecraft = "1.18.2"
quilt = "0.16.0-beta.7"
