name = "BlanketCon 2022"
author = "The community!"
version = "2022.05.06"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "680dbac12c4c4934566245f8675a6603e45e22cfab07c2bc4f1efc82eea04366"

[versions]
minecraft = "1.18.2"
quilt = "0.16.0-beta.16"
