name = "BlanketCon 2022"
author = "The community!"
version = "2022.04.20"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ab8f66b082015d2e38e1875469ab9fe20f0d31dd675c95bab9d64db8a93e75ac"

[versions]
minecraft = "1.18.2"
quilt = "0.16.0-beta.7"
