name = "BlanketCon 2022"
author = "The community!"
version = "2022.04.27"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f0466bb669d850849f350dc6916f0b4f8df81dc0051b7c2abd2720ddd1727fcb"

[versions]
minecraft = "1.18.2"
quilt = "0.16.0-beta.14"
