name = "BlanketCon 2022"
author = "The community!"
version = "2022.04.03"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1aba56c86c9b450b152e348db561d885b49db41a8552a91c359f6ae3358660fb"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
