name = "BlanketCon 2022"
author = "The community!"
version = "2022.04.26"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9532ecea13b3ffb92091a75ebafa9d634c6f36785c7b468f61a3a9f59c49325c"

[versions]
minecraft = "1.18.2"
quilt = "0.16.0-beta.13"
