name = "BlanketCon 2022"
author = "The community!"
version = "2022.04.15"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7be1103b339133411de1a51db63868df61c86eaf90f7d2c1c909a4d206ad4264"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
