name = "BlanketCon 2022"
author = "The community!"
version = "2022.04.27"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b7a1aaaeed56c03c2061b117f6ecf877cf668c675637178007e13ba363a3ff62"

[versions]
minecraft = "1.18.2"
quilt = "0.16.0-beta.13"
