name = "BlanketCon 2022"
author = "The community!"
version = "2022.04.18"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7c86f7d2ab6b74aba67fcf13ec7834e892213f55e0aaa79b5884e4988ab79ee6"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
