name = "BlanketCon 2022"
author = "The community!"
version = "2022.04.28"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a3886ad61ba87de6289c0e32f3b213fbc7635cb928d6c1ef92fdf7cd6c18e789"

[versions]
minecraft = "1.18.2"
quilt = "0.16.0-beta.14"
