name = "BlanketCon 2022"
author = "The community!"
version = "2022.04.06"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4315c4ddc21956746cb9622e2629ce41f53557252a88288e8e00287daacfce6a"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
