name = "BlanketCon 2022"
author = "The community!"
version = "2022.04.27"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e7c737716dea4d784f69aadc62244c647d0142a117eeb7526f13921364b4b13a"

[versions]
minecraft = "1.18.2"
quilt = "0.16.0-beta.14"
