name = "BlanketCon 2022"
author = "The community!"
version = "2022.04.07"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cec582e0c64c7d899a7ae0a8c95240365e6086d27b475b82b616eab283cd25fb"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
