name = "BlanketCon 2022"
author = "The community!"
version = "2022.05.01"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2b5fd6fe283ecc7599a4d054192fbdc00388785c2547e774ccc16d18fc7fd163"

[versions]
minecraft = "1.18.2"
quilt = "0.16.0-beta.16"
