name = "BlanketCon 2022"
author = "The community!"
version = "2022.04.15"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "abe8cb41f3192eadb3015bacc5f3f413724eabd9c3621b6abcfa0114594d0bda"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
