name = "BlanketCon 2022"
author = "The community!"
version = "2022.04.24"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "de922e38d63f003de8971e69cf156bb9aa519c589bba0f133f3c80649b125c92"

[versions]
minecraft = "1.18.2"
quilt = "0.16.0-beta.11"
