name = "BlanketCon 2022"
author = "The community!"
version = "2022.04.02"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bcd32fb7aadd9c47ce95da273bcb41b057249176a66595511afee2ca9ab73d64"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
