name = "BlanketCon 2022"
author = "The community!"
version = "2022.04.20"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b20f562ebfc529658020688b3a84310b95fa13278099f9fb20fb0cb2f5eae596"

[versions]
minecraft = "1.18.2"
quilt = "0.16.0-beta.7"
