name = "BlanketCon 2022"
author = "The community!"
version = "2022.04.07"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "80d0d2c2169ba928934a4643d9af4615eadf4a4acecf3c5fa5048f260916884a"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
