name = "BlanketCon 2022"
author = "The community!"
version = "2022.05.01"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d7db85b7c9eb5dfda311e388ed656e6bf7c8817ec6229a03ae4a20dfe3cf997c"

[versions]
minecraft = "1.18.2"
quilt = "0.16.0-beta.16"
