name = "BlanketCon 2022"
author = "The community!"
version = "2022.04.03"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a45c0a45b811c5d0efb63107b61b2fc1133bedca6ab4742b267744bd0b06adad"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
