name = "BlanketCon 2022"
author = "The community!"
version = "2022.04.29"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e966c469d340e40b8136a0a8a8c22fb13fd5c8313a0305b207b0caf2a0f2a3ea"

[versions]
minecraft = "1.18.2"
quilt = "0.16.0-beta.15"
