name = "BlanketCon 2022"
author = "The community!"
version = "2022.04.02"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e6f54e45b1e80a9f4e8054c41d49932369e55850d1affa9a2adc62f425ddfd8d"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
