name = "BlanketCon 2022"
author = "The community!"
version = "2022.04.07"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4ceb67c29d1ef8b2478efcb02b8b1dd718ee717952c76352eda1689450543d88"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
