name = "BlanketCon 2022"
author = "The community!"
version = "2022.04.02"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "768da1aa8ead32a4c3028dede5cf63dc735738ab5d5e96c09a2349f4ee027c70"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
