name = "BlanketCon 2022"
author = "The community!"
version = "2022.04.07"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b32d62aefe0e041c883b352cee468e414617ce1c4ee39ee97ba582657cef12c2"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
