name = "BlanketCon 2022"
author = "The community!"
version = "2022.04.23"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f590c88c748c56284ba98bf5dd1cfd849b02322757780725048fc2f6ad99c7ba"

[versions]
minecraft = "1.18.2"
quilt = "0.16.0-beta.10"
