name = "BlanketCon 2022"
author = "The community!"
version = "2022.05.03"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc54b8619f636ca13aef711ac1efcf9f7c5b14382335f37a8b89dc62a4b534f3"

[versions]
minecraft = "1.18.2"
quilt = "0.16.0-beta.16"
