name = "Archon"
filename = "archon-0.2.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3735/542/archon-0.2.3.jar"
hash-format = "sha1"
hash = "2026b1d8581d5d145eea2db6b2a5b1628e24948d"

[update]
[update.curseforge]
file-id = 3735542
project-id = 575339
