name = "Aurora's Decorations"
filename = "aurorasdecorations-1.0.0+1.18.jar"
side = "both"

[download]
url = "https://cdn.discordapp.com/attachments/745979270748307458/968604232104177664/aurorasdecorations-1.0.01.18.jar"
hash-format = "sha1"
hash = "3ccfc945606ec5ccdc48ea128d853102bc0fc846"
