name = "Aurora's Decorations"
filename = "aurorasdecorations-1.0.0+1.18.jar"
side = "both"

[download]
url = "https://cdn.discordapp.com/attachments/968595769353457725/968596665252577321/aurorasdecorations-1.0.01.18.jar"
hash-format = "sha1"
hash = "fe75adb1c20460f265aaae1eceb06647f9631ac8"
