name = "Bewitchment"
filename = "bewitchment-1.18-18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3776/650/bewitchment-1.18-18.jar"
hash-format = "sha1"
hash = "8be6f2e5f3a28ac88f0a58b08f2676cb8e2dacd9"

[update]
[update.curseforge]
file-id = 3776650
project-id = 394915
