name = "Bewitchment"
filename = "bewitchment-1.18-19.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3778/159/bewitchment-1.18-19.jar"
hash-format = "sha1"
hash = "31860bb68e833e8dff74a563d9dccd0fa78159f0"

[update]
[update.curseforge]
file-id = 3778159
project-id = 394915
