name = "Bewitchment Plus"
filename = "bewitchmentplus-1.18.2-14.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3770/844/bewitchmentplus-1.18.2-14.jar"
hash-format = "sha1"
hash = "367d37ad44e780b90c92ac7ef55b129cbf7a8cc3"

[update]
[update.curseforge]
file-id = 3770844
project-id = 582588
