name = "Bewitchment Plus"
filename = "bewitchmentplus-1.18.2-15.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3771/202/bewitchmentplus-1.18.2-15.jar"
hash-format = "sha1"
hash = "957bea3ecec6ee52294bb3a3619383581b9abd86"

[update]
[update.curseforge]
file-id = 3771202
project-id = 582588
