name = "Bewitchment Plus"
filename = "bewitchmentplus-1.18.2-11.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3768/835/bewitchmentplus-1.18.2-11.jar"
hash-format = "sha1"
hash = "26f406ec95c29cebe8dfed686dcad632b0df648a"

[update]
[update.curseforge]
file-id = 3768835
project-id = 582588
