name = "Bewitchment Plus"
filename = "bewitchmentplus-1.18.2-8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3767/886/bewitchmentplus-1.18.2-8.jar"
hash-format = "sha1"
hash = "0d1a01ed58f367af53ea93f0f9e8cfbcaf619bae"

[update]
[update.curseforge]
file-id = 3767886
project-id = 582588
