name = "Bits And Chisels"
filename = "bitsandchisels-2.6.7.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3739/965/bitsandchisels-2.6.7.jar"
hash-format = "sha1"
hash = "fbb3c073f6754a5bb4761f9ae4405d5c2576ee50"

[update]
[update.curseforge]
file-id = 3739965
project-id = 420709
