name = "cardstock"
filename = "cardstock-1.0.4.jar"
side = "both"

[download]
url = "https://github.com/repulica/CardStock/releases/download/1.0.4/cardstock-1.0.4.jar"
hash-format = "sha1"
hash = "c4847b5b2e76680aa6ed1e61d923990fae3b980f"
