name = "CC: Restitched"
filename = "cc-restitched-1.100.5+birdhouse-in-your-soul.jar"
side = "both"

[download]
url = "https://cdn.discordapp.com/attachments/968781492899704862/971550379743535135/cc-restitched-1.100.5birdhouse-in-your-soul.jar"
hash-format = "sha1"
hash = "78daf709bdae4858d373b4b097817753a4b49098"
