name = "CC: Restitched"
filename = "cc-restitched-1.100.5applause-applause-applause.jar"
side = "both"

[download]
url = "https://cdn.discordapp.com/attachments/968781492899704862/971389912123310130/cc-restitched-1.100.5applause-applause-applause.jar"
hash-format = "sha1"
hash = "8eea645cea9913b43054f41a887ee42ce9a10e34q"
