name = "Chocolate Bar"
filename = "chocolatebar-v0.1.3+mc1.18.2.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/Vyk5EM4l/versions/v0.1.3+mc.1.18.2/chocolatebar-v0.1.3%2Bmc1.18.2.jar"
hash-format = "sha1"
hash = "6a892dee4f31b7749be84170e07bc66e05e89bfc"

[update]
[update.modrinth]
mod-id = "Vyk5EM4l"
version = "fleI5rNs"
