name = "Chocolate Bar"
filename = "chocolatebar-v0.1.1+mc1.18.2.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/Vyk5EM4l/versions/v0.1.1+mc1.18.2/chocolatebar-v0.1.1%2Bmc1.18.2.jar"
hash-format = "sha1"
hash = "c0589fe43415d51ef0c408ad8dfbcbc730cb4e7d"

[update]
[update.modrinth]
mod-id = "Vyk5EM4l"
version = "pgzhCk0R"
