name = "Consistency+"
filename = "consistency_plus-0.5.0-RC2+1.18.2-fabric.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/nDHcEOt3/versions/0.5.0-RC2+Fabric-1.18.2/consistency_plus-0.5.0-RC2%2B1.18.2-fabric.jar"
hash-format = "sha1"
hash = "3ba67d4f89869f024e329fc7bc95c5b6670b3104"

[update]
[update.modrinth]
mod-id = "nDHcEOt3"
version = "vnDDBfmy"
