name = "Dyeable Fishing Lines"
filename = "DyeableFishingLines-Forge-1.0.0.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/xLgoFE2s/versions/1.0.0+forge/DyeableFishingLines-Forge-1.0.0.jar"
hash-format = "sha1"
hash = "83d9ad9bcabeb7bb1791497a174f5f2ef49a58a0"

[update]
[update.modrinth]
mod-id = "xLgoFE2s"
version = "nnZqAAeh"
