name = "Earthbounds"
filename = "earthbounds-1.1.0a.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3751/211/earthbounds-1.1.0a.jar"
hash-format = "sha1"
hash = "7a05ff23db26a7f1d4fbb39c3edde8619958a3dc"

[update]
[update.curseforge]
file-id = 3751211
project-id = 574411
