name = "Enchancement"
filename = "enchancement-1.18-9.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3781/941/enchancement-1.18-9.jar"
hash-format = "sha1"
hash = "ae8afb51864d4035f651e13f0ef75aab46ab43b0"

[update]
[update.curseforge]
file-id = 3781941
project-id = 598056
