name = "End Goblin Traders (Fabric)"
filename = "end-goblin-traders-1.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3755/77/end-goblin-traders-1.5.jar"
hash-format = "sha1"
hash = "49ddc1156d72a2c9b469a0d7907c7229b5d69658"

[update]
[update.curseforge]
file-id = 3755077
project-id = 537653
