name = "Extended Drawers"
filename = "ExtendedDrawers-1.0.2+mc.1.18.2.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/AhtxbnpG/versions/1.0.2/ExtendedDrawers-1.0.2%2Bmc.1.18.2.jar"
hash-format = "sha1"
hash = "2bd6a8c9521b67aadb1560fc182c6f8910c2b604"

[update]
[update.modrinth]
mod-id = "AhtxbnpG"
version = "oVfKRJMm"
