name = "Extended Drawers"
filename = "ExtendedDrawers-1.0.0-SNAPSHOT.jar"
side = "both"

[download]
url = "https://github.com/MattiDragon/ExtendedDrawers/releases/download/dev/ExtendedDrawers-1.0.0-dev.jar"
hash-format = "sha1"
hash = "b82975e6e7f0f5fd4841640852b3b99c03bbab58"
