name = "Extended Drawers"
filename = "ExtendedDrawers-1.0.1+mc.1.18.2.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/AhtxbnpG/versions/1.0.1/ExtendedDrawers-1.0.1%2Bmc.1.18.2.jar"
hash-format = "sha1"
hash = "2ea55321ca0ef77330b3fe7de423a64d3f6f8d23"

[update]
[update.modrinth]
mod-id = "AhtxbnpG"
version = "i25Z4eGd"
