name = "Extended Drawers"
filename = "ExtendedDrawers-1.0.0+mc.1.18.2.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/AhtxbnpG/versions/1.0.0/ExtendedDrawers-1.0.0%2Bmc.1.18.2.jar"
hash-format = "sha1"
hash = "e95df24d60fec468835325d1e971d27103c35c43"

[update]
[update.modrinth]
mod-id = "AhtxbnpG"
version = "5c6Al96I"
