name = "Flowery Structures"
filename = "flowery-fabric-10a.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3753/713/flowery-fabric-10a.jar"
hash-format = "sha1"
hash = "2ccf7636cb77ed169bcc8c438033b9eae5ee43bc"

[update]
[update.curseforge]
file-id = 3753713
project-id = 599263
