name = "Flowery Structures"
filename = "flowery-fabric-6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3738/268/flowery-fabric-6.jar"
hash-format = "sha1"
hash = "787a2a22db108707783b970a96a237ccffabe94b"

[update]
[update.curseforge]
file-id = 3738268
project-id = 599263
