name = "GeckoLib"
filename = "geckolib-quilt-1.18-3.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3761/11/geckolib-quilt-1.18-3.0.0.jar"
hash-format = "sha1"
hash = "ddafecf5653dbcd0c8733016bb485971d34da5cd"

[update]
[update.curseforge]
file-id = 3761011
project-id = 388172
