name = "GeckoLib"
filename = "geckolib-fabric-1.18-3.0.37.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3752/390/geckolib-fabric-1.18-3.0.37.jar"
hash-format = "sha1"
hash = "cc4efc700d643a3ce943400a7897e08fa1703f3e"

[update]
[update.curseforge]
file-id = 3752390
project-id = 388172
