name = "Get Off My Lawn ReServed"
filename = "goml-1.5.0-beta.3+1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3724/612/goml-1.5.0-beta.3+1.18.2.jar"
hash-format = "sha1"
hash = "c50f6a84e1b52613b22d76bf9f42f1554914fa41"

[update]
[update.curseforge]
file-id = 3724612
project-id = 572651
