name = "Get Off My Lawn ReServed"
filename = "goml-1.5.0-beta.4+1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3755/718/goml-1.5.0-beta.4+1.18.2.jar"
hash-format = "sha1"
hash = "b31e9c815aca7f9039b47c2ae95a104707cc95dc"

[update]
[update.curseforge]
file-id = 3755718
project-id = 572651
