name = "Grapple"
filename = "grapple-1.0.0+unapatched.jar"
side = "both"

[download]
url = "https://unascribed.com/f/4ec5fb3c/grapple-1.0.0+unapatched.jar"
hash-format = "sha1"
hash = "fd843eebb2e447e99595834a4eb63cc792ec53c7"
