name = "Guard Villagers (Fabric)"
filename = "guard-villagers-fabric-1.18.2-1.0.11.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3723/743/guard-villagers-fabric-1.18.2-1.0.11.jar"
hash-format = "sha1"
hash = "96197096a9cd03c8c7c10e117cbcd77b14cd050d"

[update]
[update.curseforge]
file-id = 3723743
project-id = 571503
