name = "Haema"
filename = "haema-1.9.2+1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3768/503/haema-1.9.2+1.18.2.jar"
hash-format = "sha1"
hash = "e5e684563626f3be93b689105e92cd9793bc281f"

[update]
[update.curseforge]
file-id = 3768503
project-id = 391257
