name = "Halfdoors"
filename = "half-doors-1.18.2-fabric-1.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3741/464/half-doors-1.18.2-fabric-1.1.0.jar"
hash-format = "sha1"
hash = "aad72d9cc3c328eb303bb0b756555e1709d88da5"

[update]
[update.curseforge]
file-id = 3741464
project-id = 596375
