name = "Halfdoors"
filename = "half-doors-1.18.2-fabric-1.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3704/145/half-doors-1.18.2-fabric-1.0.0.jar"
hash-format = "sha1"
hash = "23b8eab1f1132fe2613360f824e483a3dd724547"

[update]
[update.curseforge]
file-id = 3704145
project-id = 596375
