name = "Icy Incitement"
filename = "icy-incitement-1.18.2-fabric-1.1.1.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/Zj1ND0rS/versions/1.1.1/icy-incitement-1.18.2-fabric-1.1.1.jar"
hash-format = "sha1"
hash = "d885936417df7532b9a309943c51effbb6ed51e8"

[update]
[update.modrinth]
mod-id = "Zj1ND0rS"
version = "oXQBdwC3"
