name = "Incorporeal 3"
filename = "Incorporeal-3-fabric-1.18.2-0-SNAPSHOT-bb0c0a9e+now-with-refmap.jar"
side = "both"

[download]
url = "https://unascribed.com/f/d0ebdd7f/Incorporeal-3-fabric-1.18.2-0-SNAPSHOT-bb0c0a9e+now-with-refmap.jar"
hash-format = "sha1"
hash = "4fbed0a514d07f52630a48f1981e3a0ce8da73d6"
