name = "Jamtastic"
filename = "jamtastic-1.3.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3763/904/jamtastic-1.3.4.jar"
hash-format = "sha1"
hash = "d4d74ea3b990c8dfa69fd45f56a787788477483b"

[update]
[update.curseforge]
file-id = 3763904
project-id = 559060
