name = "Jamtastic"
filename = "Jamtastic-1.3.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3760/942/Jamtastic-1.3.2.jar"
hash-format = "sha1"
hash = "f7d5f67da0314528a4c4de5f17bd055e2b80ef8a"

[update]
[update.curseforge]
file-id = 3760942
project-id = 559060
