name = "Jamtastic"
filename = "Jamtastic-1.3.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3751/219/Jamtastic-1.3.1.jar"
hash-format = "sha1"
hash = "6a733bcf5d608457c2366758e774cf2934bbbed7"

[update]
[update.curseforge]
file-id = 3751219
project-id = 559060
