name = "Now Playing"
filename = "now-playing-fabric-1.4.0.jar"
side = "client"

[download]
url = "https://cdn.discordapp.com/attachments/958513632419938394/959877049210781706/now-playing-fabric-1.4.0.jar"
hash-format = "sha1"
hash = "89b515bea4fd44ff5a3bbef91da7f7948506570a"
