name = "oÏ‰o (owo-lib)"
filename = "owo-lib-0.7.1+1.18.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/ccKDOlHs/versions/0.7.1+1.18/owo-lib-0.7.1%2B1.18.jar"
hash-format = "sha1"
hash = "d28904b3cb8d5f9a389d9ebdae1d3f4ccc144db6"

[update]
[update.modrinth]
mod-id = "ccKDOlHs"
version = "WJsP5KWE"
