name = "oÏ‰o (owo-lib)"
filename = "owo-lib-0.7.0+1.18.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/ccKDOlHs/versions/0.7.0+1.18/owo-lib-0.7.0%2B1.18.jar"
hash-format = "sha1"
hash = "cef12ddbc4c9817e0fd9843be14418f0195df76c"

[update]
[update.modrinth]
mod-id = "ccKDOlHs"
version = "zVhs4uLj"
