name = "PolaroidCamera"
filename = "polaroidcamera-1.2.2.jar"
side = "both"

[download]
url = "https://github.com/HyperPigeon/PolaroidCamera/releases/download/v1.2.2/polaroidcamera-1.2.2.jar"
hash-format = "sha1"
hash = "a73817a69aa4d22be72aa6c9dc6b733a93ea44f7"
