name = "Polaroid Camera "
filename = "polaroidcamera-1.2.3.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/9dPDuh0K/versions/v1.2.3/polaroidcamera-1.2.3.jar"
hash-format = "sha1"
hash = "71558ae2772c137425db9bb26eae7c1fc27bc035"

[update]
[update.modrinth]
mod-id = "9dPDuh0K"
version = "wTPVu10T"
