name = "PolaroidCamera"
filename = "polaroidcamera-1.2.1.jar"
side = "both"

[download]
url = "https://github.com/HyperPigeon/PolaroidCamera/releases/download/v1.2.1/polaroidcamera-1.2.1.jar"
hash-format = "sha1"
hash = "7b39a0b5faac152d530e3d452a820295bb5f872c"
