name = "PolyMc Showcase"
filename = "polymcshowcase-1.1.0.jar"
side = "both"

[download]
url = "https://github.com/TheEpicBlock/PolyMcShowcase/releases/download/1.1.0/polymcshowcase-1.1.0.jar"
hash-format = "sha1"
hash = "371654446531971a0ecd5141641dd9d6a372b4e6"
