name = "PolyMc"
filename = "PolyMc-4.1.2+1.18.2.jar"
side = "server"

[download]
url = "https://maven.theepicblock.nl/nl/theepicblock/PolyMc/4.1.2%2B1.18.2/PolyMc-4.1.2%2B1.18.2.jar"
hash-format = "sha1"
hash = "40306eb632a05db30d1f5f0c08da3a30fba8ef56"
