name = "PolyMc"
filename = "PolyMc-4.1.1+1.18.2.jar"
side = "server"

[download]
url = "https://maven.theepicblock.nl/nl/theepicblock/PolyMc/4.1.1%2B1.18.2/PolyMc-4.1.1%2B1.18.2.jar"
hash-format = "sha1"
hash = "5add93d45ab2dd567a16e9f165c6ea61f07a7811"
