name = "PolyMc Showcase"
filename = "polymcshowcase-1.1.2.jar"
side = "both"

[download]
url = "https://github.com/TheEpicBlock/PolyMcShowcase/releases/download/1.1.2/polymcshowcase-1.1.2.jar"
hash-format = "sha1"
hash = "faa2526124df3f51c02b3bc3dc0ade249c811391"
