name = "PolyMc"
filename = "PolyMc-4.1.2-rev.99509b5+1.18.2.jar"
side = "server"

[download]
url = "https://maven.theepicblock.nl/nl/theepicblock/PolyMc/4.1.2-rev.99509b5%2B1.18.2/PolyMc-4.1.2-rev.99509b5%2B1.18.2.jar"
hash-format = "sha1"
hash = "d3b2c491c21fa7a27ba8c11863f5c1cb30929d42"
