name = "PolyMc Showcase"
filename = "polymcshowcase-1.1.1.jar"
side = "both"

[download]
url = "https://github.com/TheEpicBlock/PolyMcShowcase/releases/download/1.1.1/polymcshowcase-1.1.1.jar"
hash-format = "sha1"
hash = "0150e484d2e889160c9db743a4ac1f8413ae5645"
