name = "PolyMc"
filename = "PolyMc-4.1.0+1.18.2.jar"
side = "server"

[download]
url = "https://maven.theepicblock.nl/nl/theepicblock/PolyMc/4.1.0%2B1.18.2/PolyMc-4.1.0%2B1.18.2.jar"
hash-format = "sha1"
hash = "e7d4ab05304625c4c6caac0f4e25f1a7bbc66d2f"
