name = "PolyMc"
filename = "PolyMc-4.0.0+1.18.2.jar"
side = "server"

[download]
url = "https://github.com/TheEpicBlock/PolyMc/releases/download/4.0.0/PolyMc-4.0.0+1.18.2.jar"
hash-format = "sha1"
hash = "a72559bcdfb54b293f354a49ae219f8930d91019"
