name = "Refined Magic"
filename = "refmagic-1.0.0.jar"
side = "both"

[download]
url = "https://cdn.discordapp.com/attachments/745979270748307458/967888448524542062/refmagic-1.0.0.jar"
hash-format = "sha1"
hash = "d2fc7ed2978bb67edafcf0088bcf62726da101af"
