name = "Oliver's Potion Tweaks"
filename = "potion-tweaks-1.0.0.jar"
side = "both"

[download]
url = "https://cdn.discordapp.com/attachments/745979270748307458/964599674549993502/potion-tweaks-1.0.0.jar"
hash-format = "sha1"
hash = "e80b5275d23f12b793c67dbff3af80d02c403a4c"
