name = "Galaxies: Parzi's Star Wars Mod"
filename = "pswg-0.0.66+1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3748/597/pswg-0.0.66+1.18.2.jar"
hash-format = "sha1"
hash = "2f1169a64f41014c41ba7628e075c293d7e9d30d"

[update]
[update.curseforge]
file-id = 3748597
project-id = 496522
