name = "Galaxies: Parzi's Star Wars Mod"
filename = "pswg-0.0.64+1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3717/462/pswg-0.0.64+1.18.2.jar"
hash-format = "sha1"
hash = "5371c01694e40208d87032523c4ff56d2c3b1394"

[update]
[update.curseforge]
file-id = 3717462
project-id = 496522
