name = "qCraft Reimagined"
filename = "qcraft-1.0.0.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/uwzLLQUA/versions/1.0.0/qcraft-1.0.0.jar"
hash-format = "sha1"
hash = "d827af9e23bf73d5a5b43ce6e5822ccf25c97b27"

[update]
[update.modrinth]
mod-id = "uwzLLQUA"
version = "AqYF3BOt"
