name = "Reaping Mod"
filename = "reaping-1.7.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3770/927/reaping-1.7.1.jar"
hash-format = "sha1"
hash = "ff26eafc3589796813ed22587b48429e2d02adc7"

[update]
[update.curseforge]
file-id = 3770927
project-id = 485532
