name = "Reaping"
filename = "reaping-2.0.0+fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3775/366/reaping-2.0.0+fabric.jar"
hash-format = "sha1"
hash = "e55cf430fcfcf30a63bd34b057d6206269068757"

[update]
[update.curseforge]
file-id = 3775366
project-id = 485532
