name = "Reaping"
filename = "reaping-2.0.1+fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3779/501/reaping-2.0.1+fabric.jar"
hash-format = "sha1"
hash = "5720bab9fe8fc0fbf608bef30412cb44e1f493c3"

[update]
[update.curseforge]
file-id = 3779501
project-id = 485532
