name = "Refined Magic"
filename = "refmagic-1.0.0-beta4.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/yTtdp6Mq/versions/1.0.0-beta4/refmagic-1.0.0-beta4.jar"
hash-format = "sha1"
hash = "c9f8b40da644a67e2392b364b09a9b392554cc25"

[update]
[update.modrinth]
mod-id = "yTtdp6Mq"
version = "C99KWpx7"
