name = "Smithy"
filename = "Smithy-1.0-pre+blanketcon.1.jar"
side = "both"

[download]
url = "https://unascribed.com/f/56663ac9/Smithy-1.0-pre+blanketcon.1.jar"
hash-format = "sha1"
hash = "3c5c3e7cd8a63414b0257961022396604111fba9"
