name = "Smithy"
filename = "Smithy-1.0-pre+blanketcon.2.jar"
side = "both"

[download]
url = "https://unascribed.com/f/21e8e419/Smithy-1.0-pre+blanketcon.2.jar"
hash-format = "sha1"
hash = "35d62405fc90cbbc066fa19142a77bc58f4cbbc4"
