name = "Smithy"
filename = "Smithy-1.0-pre2+IHate1.18.2-nocustom.jar"
side = "both"

[download]
url = "https://unascribed.com/f/5c59d891/Smithy-1.0-pre2+IHate1.18.2-nocustom.jar"
hash-format = "sha1"
hash = "91cb7bc8057dee71d71eb89092805e23d769ec60"
