name = "Soul Ice"
filename = "soulice-1.0.0+1.18.2-fabric.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/ngBlYV53/versions/1.0.0+Fabric-1.18/soulice-1.0.0%2B1.18.2-fabric.jar"
hash-format = "sha1"
hash = "d6d9400d1efe18508139457ee9460d843dc623a9"

[update]
[update.modrinth]
mod-id = "ngBlYV53"
version = "Vbqll28w"
