name = "Soul Ice"
filename = "soulice-1.2.0+1.18.2-fabric.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/ngBlYV53/versions/1.2.0+Fabric-1.18.2/soulice-1.2.0%2B1.18.2-fabric.jar"
hash-format = "sha1"
hash = "114fce9818d14754b3e047624dde50bde20445e4"

[update]
[update.modrinth]
mod-id = "ngBlYV53"
version = "AA9BTg69"
