name = "Taterzen NPCs"
filename = "taterzens-1.9.0-fabric.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/vE972Kux/versions/1.18.2+1.9.0-fabric/taterzens-1.9.0-fabric.jar"
hash-format = "sha1"
hash = "5ba5438bba04edc8b8d0ef05f714a1d63e0a959d"

[update]
[update.modrinth]
mod-id = "vE972Kux"
version = "pAuMxZYE"
