name = "ThonkUtil"
filename = "thonkutil-2.13.1+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3778/527/thonkutil-2.13.1+1.18.jar"
hash-format = "sha1"
hash = "62d4867a8709fd75df4aa438069d4d0f9926496d"

[update]
[update.curseforge]
file-id = 3778527
project-id = 536648
