name = "WorldEdit"
filename = "worldedit-mod-7.2.10-nonetworkingapi.jar"
side = "both"

[download]
url = "https://cdn.discordapp.com/attachments/745979270748307458/962411862224412722/worldedit-mod-7.2.10-nonetworkingapi.jar"
hash-format = "sha1"
hash = "01a85066bcd0ad451dd45594710a25bbf6c00b20"
